spring.application.name=KinalApp


#Conexion MySQL
spring.datasource.url = jdbc:mysql://localhost:3306/dbClientes_in5av?createDatabaseIfNotExist=true
spring.datasource.username = IN5AV
spring.datasource.password = !+admin5av
#Spring.datasource.username=root
#Spring.datasource.password=botas2701
server.port=8001

#JPA / hibernate
Spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true